### ISSUE TITLE
Build Complete but cant run

### ISSUE THREAD

**Issue by silicahd** [alejandrods/text-generation-gpt2#1]
So after a lot of work I got it to build. However when I run the last command the entire thing just fails. Maybe I am missing something. Any ideas.
```

PS C:\Users\VirgilTu\desktop\ai\text-generation-gpt2-master> docker run --name text-generator-gpt2 --env-file=.env -p 8080:8080 text-generator-gpt2
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/transformers/configuration_utils.py", line 242, in get_config_dict
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from generate import generate
  File "/usr/app/generate.py", line 13, in <module>
    tokenizer = AutoTokenizer.from_pretrained("./distilgpt2")
  File "/usr/local/lib/python3.6/site-packages/transformers/tokenization_auto.py", line 206, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/transformers/configuration_auto.py", line 203, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/transformers/configuration_utils.py", line 251, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for './distilgpt2'. Make sure that:

- './distilgpt2' is a correct model identifier listed on 'https://huggingface.co/models'

- or './distilgpt2' is the correct path to a directory containing a config.json file

```

**Comment by chungnq253** [comment]
I have the same problem.

**Comment by kirkins** [comment]
Same here

**Comment by alejandrods** [comment]
In the script `generate.py`, you need to change the name of the model in the line `tokenizer = AutoTokenizer.from_pretrained(<THE PATH TO YOUR MODEL>)`

I hope this helps you.
